Update CI workflow and removed Jenkinsfile

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -55,8 +55,8 @@ jobs:
             echo "::set-output name=state::master"
           fi
                   
-  notify:
-    name: Slack notification
+  start-notify:
+    name: Start build notification with Slack
     runs-on: ubuntu-latest
     needs: [configure]
     steps:
@@ -95,6 +95,10 @@ jobs:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
     needs: [configure]
+    outputs:
+      default: ${{ steps.save.outputs.default }}
+      k8s: ${{ steps.save.outputs.pcn-k8s }}
+      iptables: ${{ steps.save.outputs.pcn-iptables }}
     # Build strategies
     strategy:
       matrix:
@@ -166,30 +170,12 @@ jobs:
 
       - name: Image digest
         run: echo ${{ steps.docker_build.outputs.digest }}
-      
-      - name: Notify on slack the build outcome
-        uses: 8398a7/action-slack@v3
-        with:
-          status: custom
-          fields: workflow
-          custom_payload: |
-            {
-              "attachments":[
-                  {
-                    "title":`${process.env.AS_WORKFLOW}`,
-                    "text": "Build of polycube with *${{ matrix.mode }}* mode, finished",
-                    "color": '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
-                    "fields":[{
-                          "title":"Check suite",
-                          "value":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-                        }
-                      ]
-              }]
-            }
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-        if: always() # Pick up events even if the job fails or is canceled.
-  
+
+      - name: Save build result in output
+        id: save
+        if: always()
+        run: |
+          echo "::set-output name=${{ matrix.mode }}::${{ job.status }}"
   
   # This job deal with tests
   test:
@@ -198,8 +184,8 @@ jobs:
     needs: [build, configure]
     if: needs.configure.outputs.state == 'dev'
     outputs:
-      result-clean: ${{ steps.clean.outputs.default-clean }}
-      result-same: ${{ steps.clean.outputs.default-same }}
+      clean: ${{ steps.clean.outputs.default-clean }}
+      same: ${{ steps.clean.outputs.default-same }}
     # Test strategies
     strategy:
       fail-fast: false
@@ -295,6 +281,62 @@ jobs:
         run: |
           echo "::set-output name=${{ matrix.test }}::${{ steps.check.outcome }}"
           ./CI/clean_slave.sh
+
+  end-notify:
+    name: End build notification with Slack
+    runs-on: ubuntu-latest
+    needs: [configure, build, test]
+    if: always()
+    steps:
+      - name: Build result check
+        id: result
+        if: |
+          needs.build.outputs.default == 'success' &&
+          needs.build.outputs.k8s == 'success' &&
+          needs.build.outputs.iptables == 'success' &&
+          (needs.configure.outputs.state != 'dev' || (needs.test.outputs.clean == 'success' && needs.test.outputs.same == 'success'))
+        run: echo "::set-output name=status::success"
+        
+      - name: Notify on slack the build outcome
+        uses: 8398a7/action-slack@v3
+        with:
+          status: custom
+          fields: workflow,commit,repo,ref
+          custom_payload: |
+            {
+              "attachments":[
+                  {
+                    "title":`${process.env.AS_WORKFLOW}`,
+                    "text": "Build finished",
+                    "color": '${{ steps.result.outputs.status }}' === 'success' ? 'good' : 'danger',
+                    "fields":[{
+                          "title":"Check suite",
+                          "value":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+                        },
+                        {
+                          "title":"Git reference",
+                          "value":`${process.env.AS_REPO}@${process.env.AS_REF}`,
+                        },
+                        {
+                          "title":"Commit",
+                          "value":`${process.env.AS_COMMIT}`,
+                        },
+                        {
+                          "title":"Build modes",
+                          "value":"*default* ${{ needs.build.outputs.default }}\n*pcn-k8s* ${{ needs.build.outputs.k8s }}\n*pcn-iptables* ${{ needs.build.outputs.iptables }}\n",
+                          "short": "true"
+                        },
+                         {
+                          "title":"Test modes",
+                          "value": '${{ needs.configure.outputs.state }}' != 'dev' ? "skipped" : "*default clean* ${{ needs.test.outputs.clean }}\n*default same* ${{ needs.test.outputs.same }}",
+                          "short": "true"
+                        }
+                      ]
+              }]
+            }
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+        if: always() # Pick up events even if the job fails or is canceled.
 
   release:
     name: Release Polycube
